---
# Uncomment and change values to override defaults

# Linux
#
# Set a custom song directory
#song_path: /home/{username}/.local/share/karaoke-rs/songs
#
# Set a custom data directory
#data_path: /home/{username}/.local/share/karaoke-rs

# Windows
#
#song_path: C:/Users/{username}/AppData/Roaming/karaoke-rs/songs
#data_path: C:/Users/{username}/AppData/Roaming/karaoke-rs

# Disable collection refresh on startup (helpful if collection is huge and not changing)
#no_collection_update: false

# Use web player instead of native player (playable from any browser)
#use_web_player: false